#ifndef BINARY_STAGE_PARSER_DEFS_H
#define BINARY_STAGE_PARSER_DEFS_H

#define ADDR_TYPE uint64_t

enum {
	DEFAULT_BINARY_DATA_SIZE = 15888U,
	IMPROVED_BINARY_DATA_SIZE = 16992U,
	DEFAULT_BINARY_DATA_STAGES_AMOUNT = 20U,
	IMPROVED_BINARY_DATA_STAGES_AMOUNT = 19U
};

#endif
